### ISSUE TITLE
Boxes

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/rtype#119]
Lots of types contain other types. For example, `Promise` represents a value of some type.

An array can have typed values in it, which we currently represent like:

```
[...Number]
```

What if you could also do:

```
Promise[Number]
```

Or:

```
Functor[...Number]
```

I'm banging my head against this now, because I'm trying to translate a variety of functional signatures to rtype, and I'm struggling. Here's what I've got. The functor map signature is defined as:

```
fmap :: (a -> b) -> f a -> f b
```

Given a function that takes an `a` and returns a `b` and a box with one or more `a`s  inside it: `fmap` returns a box with one or more `b`s inside it.

Let's try to translate that to an rtype-like signature:

```js
fmap(a => b) => Functor[...a] => Functor[...b]
```

Does that look interesting? I honestly find it more readable than the Haskell version (though the Haskell version is attractively concise!)

Another point here. In the Haskell version, `a` and `b` represent type variables. The actual type of `a` and `b` are unspecified, but `a` and `b` represent *types*, not *parameter names*.

Does our current grammar allow for this translation?

**Comment by nickytonline** [comment]
In TypeScript, for your promise example, you would use a generic,  `Promise<T>` e.g.  `Promise<number>`.  Same goes for you number array example.  It would be `number[] ` or `Array<number>`. For your functor, you'd declare an interface that contains a typed signature.

**Comment by Mouvedia** [comment]
Ill take the problem from another angle; shouldn't we want to single out that use case clearly?
The usage of the fat arrow in all of our examples is final: it indicates the returned type. You don't scan backwards from the end of the last word to find the type, it's LTR 101.

Now what I am saying is that—since [*this is not javascript*](https://github.com/ericelliott/rtype/pull/115#issuecomment-252779363)—we could carry over the `->` convention from other functional languages, like Elm. That would be immediately familiar to the users most likely to use these kind of signatures and would have the added benefit of being more readable as explained above.

Concerning #115, I don't consider #119 a blocker.

**Comment by ericelliott** [comment]
@nickytonline I'm aware of TypeScript's treatment of generics. Can you show me how you express the Functor signature in TypeScript? That's where I get a little lost.

@Mouvedia:

> The usage of the fat arrow in all of our examples is final: it indicates the returned type.

I'm confused -- that's exactly how the fat arrow is used here:

```
fmap(a => b) => Functor[...a] => Functor[...b]
```
I'll repeat the prose description, with emphasis for arrows:

> Given a function that (takes an `a` and **returns a `b`**), and a box with one or more `a`s inside it [insert implicit `=>` here]: fmap **returns a box** with one or more `b`s inside it.

Note that this signature is for an auto-curried form of `fmap()`, which is mostly because I wanted the most direct translation possible of Haskell's `fmap` to JavaScript.

**Comment by nickytonline** [comment]
@ericelliott, check out http://thunklife.website/blog/typescript-experiments.html

**Comment by ericelliott** [comment]
This doesn't go far enough. Closing in favor of #120
