### ISSUE TITLE
thought: this seems very similar to jsig

### ISSUE THREAD

**Issue by bcherny** [ericelliott/rtype#47]
https://github.com/jsigbiz/spec

**Comment by ericelliott** [comment]
Interesting. Maybe we should talk about merging?

**Comment by Mouvedia** [comment]
[That](https://github.com/jsigbiz/spec#compound-types-or-extends-mixins-etc)'s #9 right?

Anyway, if we take the good parts of jsig, +1.
For example I like that part about [named signatures](https://github.com/jsigbiz/spec#parameters).

Personally I find rtype way simpler and clearer in its approach. We should check it out to see what we are lacking and leave it at that.

**Comment by ericelliott** [comment]
We already have named signatures. Without the colon.

**Comment by ericelliott** [comment]
What does #9 have to do with this?

#9 is about intersection types. JSIG has competing syntax -- instead of intersection, `&` is used for polymorphic functions (which we support using the `interface` keyword block).

**Comment by ericelliott** [comment]
Maybe we can steal ideas (or even code!) from the jsig parser?

**Comment by tomek-he-him** [comment]
Perhaps the JSIG team would be willing to migrate to rtype? JSIG didn’t seem to be complete the last time I looked at it – and there hasn’t been much happening in their repos since.

CC: @Raynos @jden

**Comment by Raynos** [comment]
@tomekwi @ericelliott

Jsig has two goals. 

A human readable way to express the interface of an es3/es5 module. This was the original goal from @jden

A type checker for JavaScript. Typescript and flow are frustrating because they follow the compile to js approach. With jsig I want a type checker that takes valid es5 in and checks to see if it's type sound (no compilation). I want to strongly leverage external type definition header files without modifying the source code. I really dislike jsdoc because there should never be more comments then actual lines of code.

If rtype wants to solve these problems then we can merge.

**Comment by ericelliott** [comment]
@Raynos Yes, rtype is taking on those same goals, with one **important** additional goal: runtime type reflection, even in prod (even with type **checking** turned off).

That's important for next-gen runtime dev tools and graphical dev environments.

## About Rtype
- Great for simple documentation.
- Compiler-free type notation - for use with ECMAScript standard tools.
- Should embed in JS **as strings, not comments**. Affords **easy runtime reflection.**
- Standing on the shoulders of giants: ES6, TypeScript, Haskell, Flow, & React

See [rfx for inline/runtime support](https://github.com/ericelliott/rfx).

**Comment by ericelliott** [comment]
@Raynos @jden - we'd love to have you with us. =)

**Comment by Raynos** [comment]
@ericelliott 

I don't care about runtime type reflection. I do not want to embed strings in my javascript. If this runtime reflection feature is an "optional" feature then this can work.

As a secondary note, I also don't care about React, I want to implement a type checker for distributed nodejs applications. I don't care about extending or working with React.PropTypes for example.

**Comment by junosuarez** [comment]
This looks like a neat project, and I'm glad to see convergence of ideas around modeling structural types in JavaScript. When jsig started, TypeScript had just been released and did not have union types or generics, and flow and react did not exist. I'm happy to see more people treating types more seriously in JavaScript.

jsig does not have a good story around ES2015+ currently, but it does a decent job of describing ES5 interfaces and type signatures. As @raynos said, the original goal of jsig was for precise & concise documentation, and later to be unobtrusive and minimally invasive. Run-time type reflection is not a stated goal of jsig core, _however_ since jsig focuses on type semantics and grammar, it would be a solid base to build tooling on- for example, from a parsed jsig AST, you could generate functions to do runtime type assertions, function signature type assertion/reflection (e.g. for dependency injection), etc. 

I currently use jsig the way I always have, for the limited purpose of documenting my programs with inline function comments and in api reference documentation.

I am currently not interested in revisiting syntax decisions in jsig except to address cases from ES2015 which are not currently supported. I admit jsig could benefit from some TLC in resolving open issues and an editor to incorporate them back into the spec document.

**Comment by Raynos** [comment]
So in terms of features jsig has that we can support to rtype: 
- a working ast parser
- a working ast serializer
- a working ast builder library
- a json schema -> jsig converter. Mostly used with the ast serializer to pretty print json schema in a human readable fashion
- a proof of concept annotater. This would monkey patch the module system and wrap all your modules with runtime type checkers. The idea is that you define the signature of your module and used the annotater in your tests to assert that all call sites into the module are type correct
- a proof of concept type checker. Like the annotater but it's static; there is no runtime checks, it uses esprima and es5 type inference to verify that all call sites match the type signature.

I would be interested in merging efforts if it means that more then one person (myself) works on the type checker.

**Comment by Mouvedia** [comment]
Can the two specifications coexist? If not in which direction do we make the merge?
Obviously Id be in favor of rtype being the recipient but that's just a matter of taste.

If we do merge we will have to make a list of the things missing from the recipient (and present in the one being superseded) and the things that create fundamental incompatibilities between the competing specifications that could prevent the import of these missing features.

**Comment by Raynos** [comment]
Before we talk about how to merge let's address:
- what we are going to collaborate on, if we are not going to commit to the same repo then we are not collaborating.
- what the semantic differences are
- what the syntactic differences are

**Comment by ericelliott** [comment]
@Raynos Runtime reflection is an important feature that I need for future work, but there's nothing stopping anybody from embedding rtype in comments as long as they don't need rtype comments. ;)

Our syntax looks very similar, and it looks like we may be able to reuse a lot of the software that's already written for jsig.

I'm a bit confused about jsig's "compound types". This makes sense, with the assumption that it follows the same behavior as `Object.assign()`:

``` js
Response: ReadStream & {statusCode: Number}
```

But this doesn't make any sense at all to me. It seems like this has an ambiguous meaning:

``` js
fooAsync: (callback: Function) => Something &
    () => Promise
```

Is this like  `Object.assign(Something, Promise)` or is this a polymorphic function that sometimes returns a promise if a callback is not supplied? `rtype` has explicit notation for polymorphic functions. Just specify multiple function signatures:

``` js
interface Collection {
  (items: Array[]) => Array[],
  (items: Object[]) => Object[]
}
```

So you'd write the first example this way:

``` js
interface fooAsync {
  (callback: Function) => Something,
  () => Promise
}
```

I see you're using angle brackets for typed arrays. Fine for people from C++/Java backgrounds. I'm not a fan, though. I find them harder to read.

I'm willing to make a few concessions if it means we can use a lot of already-built software with rtype.

Looks like we support lots of similar features using similar notation. JSIG seems to be falling behind on features. Compound types looks like the only feature we don't already have in the spec, but we're already considering it.

> I am currently not interested in revisiting syntax decisions in jsig except to address cases from ES2015 which are not currently supported.

`rtype` has some great ES6 syntax that JSIG does not support. It looks like rtype is essentially a modern superset of JSIG, for the most part. The angle brackets are the only serious conflict I see at a glance. We also use `interface` instead of `type`. I think I'm willing to accept `type`. Not so sure about angle brackets, but open to discussion. TypeScript also supports angle brackets, I think.

**Comment by Raynos** [comment]
"compound types" should be seen in terms of set theory.

A value `X` is a subtype of `Response` if a value `X` is a subtype of `ReadStream` and a value `X` is a subtype of `{ statusCode: Number }`

A value `X` is a subtype of `fooAsync` if a value `X` is a subType of `(callback: Function) => Something` and a value `X` is a subtype of `() => Promise`

I think the confusion might be about

```
( (callback: Function) => Something) & () => Promise)
```

vs

```
(callback: Function) => (Something & () => Promise)
```

i.e. order preference of the operator.

**Comment by Raynos** [comment]
> I'm willing to make a few concessions if it means we can use a lot of already-built software with rtype.

I honestly don't care too much about syntax so I'm willing to convert syntax where there is no semantic difference. I'm not actively using any of the jsig tooling because the project is not complete, so a back compat breaking syntax change does not matter to me.

> JSIG seems to be falling behind on features. It looks like rtype is essentially a modern superset of JSIG, for the most part

Adding support for ES2015 features in the Parser/Serializer is not a big deal, we can do that :) 

Adding support for ES2015 to the static type checker will be painful, I wanted to focus on static type checking for ES5 and only later consider ES2015 features once ES5 features are supported and implemented.

**Comment by Raynos** [comment]
We may benefit from bringing this conversation to gitter or IRC ( I created a temporary gitter room https://gitter.im/Raynos/temp-rtype ).

**Comment by Raynos** [comment]
Another thing worth looking at is the WIP spec for jsig that defines the grammar of a jsig file and the semantics in terms of type checking ( https://github.com/jsigbiz/spec/blob/master/spec.md )

The more I think about what I really want to do with the jsig long term, the more it looks like a c-style header file. I.e. One jsig definition file for every module in a JavaScript library / application.

The other use cases are self documenting block comments in the source, jsig sections in your markdown docs or a single jsig file for an entire npm module as documentation. These use cases are all human readable only, not machine readable.

**Comment by Mouvedia** [comment]
I agree with everything @ericelliott said [there](https://github.com/ericelliott/rtype/issues/47#issuecomment-162267103).

Since you both stated what was your long term motivation. Ill share mine.
I want a tool that will leverage rtype/jsig enabling us to inject polyfills/shims and dependencies depending on the browser. Using [`requires`](https://github.com/ericelliott/rtype#dependencies) and http://polyfills.io/ it won't be that hard to pull off.

**Comment by ericelliott** [comment]
> The more I think about what I really want to do with the jsig long term, the more it looks like a c-style header file. I.e. One jsig definition file for every module in a JavaScript library / application.

Yep. I love that idea.

**Comment by jokeyrhyme** [comment]
I've been looking for a way to provide run-time type-assertions and API documentation in a way that avoids duplication. I also quite like React PropTypes, but want something that is framework-agnostic and useful for Node.js development.

**Comment by ericelliott** [comment]
Sounds like our plans for rtype support all the use-cases people have mentioned in this thread, and JSIG supports most, with the exception of some of the runtime features.

Let's talk priorities.

Right now, I'm very interested in getting rtype tokenizing/parsing working so that we can use that for the basis of our runtime type checking in [rfx](https://github.com/ericelliott/rfx).

It seems to me that most of that work could be extending the current parsing tools for jsig, making the (possibly big) assumption that in jsig, parsing and static analysis are handled in decoupled steps?

**Comment by Raynos** [comment]
Let's talk code. 
- There is a `parser.js` ( https://github.com/jsigbiz/parser/blob/master/parser.js ) that takes a text string and outputs an ast
- There is an `ast.js` module that exposes all the constructors for all the AST nodes ( https://github.com/jsigbiz/parser/blob/master/ast.js ).
- The AST actually has a well defined type signature ( https://github.com/jsigbiz/parser/blob/master/docs.mli ). 
- There a bunch of "integration tests" for the parser and ONLY the parser ( https://github.com/jsigbiz/parser/tree/master/test/parser/integration ).
- There is a seperate one-file pretty printer ( https://github.com/jsigbiz/parser/blob/master/serialize.js ) that turns an AST into text.
- I do actually have a tokenizer ( https://github.com/jsigbiz/parser/blob/master/parser/lexemes.js ). The lexemes file as part of the parser defines all the tokens.
- The type checker is a completely seperate program that uses `readAST` and operates purely on a jsig AST and an ES5 esprima AST ( https://github.com/jsigbiz/parser/blob/master/type-checker/index.js#L11 )

The parser itself is written in JavaScript using `parsimmon` ( https://github.com/jneen/parsimmon ). Here's an example of it ( https://github.com/jsigbiz/parser/blob/master/parser/statement.js )

The parsimmon library is a parser combinator library. I choose it because it allowed me to iterate on it in javascript without worrying about anything else like yacc / bison / pegjs. Although porting it to any of those might be a good idea. 

I've worked a bit with pegjs ( https://github.com/uber/thriftrw-node/blob/master/thrift-idl.pegjs ) so it could be ported to that if a declarative approach to parsing is preferable over.

One thing I would recommend re-using is all of the tests ( https://github.com/jsigbiz/parser/tree/master/test/parser ). We should port the tests over to a unified/merged rtype/jsig language and a merged/unified AST representation.

**Comment by jokeyrhyme** [comment]
I started an EBNF a few days ago, just in case I was going to be working on a tokeniser:
- https://github.com/jokeyrhyme/rtype/blob/ebnf/docs/ebnf.md

I got lazy when it came to the pieces that are literally JavaScript syntax, and those parts may or may not be time-consuming to cover. /shrug

**Comment by ericelliott** [comment]
> One thing I would recommend re-using is all of the tests ( https://github.com/jsigbiz/parser/tree/master/test/parser ). We should port the tests over to a unified/merged rtype/jsig language and a merged/unified AST representation.

This sounds like a great place to start. Are you volunteering? =)

**Comment by Raynos** [comment]
I don't have the capacity to work on this until next weekend.

But I'm down for "short hackathon" to work on merging this weekend if other people are interested and there is good timezone overlap.

**Comment by ericelliott** [comment]
I'd be willing to whip up a bunch of new test cases for `rtype` syntax that is not yet supported.

**Comment by Mouvedia** [comment]
Ill work with @Raynos on the specification merger.

**Comment by ericelliott** [comment]
> Ill work with @Raynos on the specification merger.

:+1: - I think the syntax spec needs to have consensus before we take a deep dive into code implementation. =)

**Comment by jokeyrhyme** [comment]
What would be "the rtype way" of defining a [generic type](https://github.com/jsigbiz/spec#generic-types)?

Also, rtype supports object spread operators, so that can be the equivalent of [compound types](https://github.com/jsigbiz/spec#compound-types-or-extends-mixins-etc):

jsig: `Response: ReadStream & {statusCode: Number}`

rtype: `interface Response { statusCode: Number, ...ReadStream }`

**Comment by Mouvedia** [comment]
> What would be "the rtype way" of defining a generic type?

https://github.com/ericelliott/rtype#array-types
Seems pretty straight forward to me. That only covers the main use case.

We will discuss the matter this weekend.

**Comment by ericelliott** [comment]
Array types only work for arrays. We don't currently support generic types, but maybe we should. =)

**Comment by Raynos** [comment]
I've spent quite a bit of time working on a static type checker based on jsig ( https://github.com/Raynos/jsig2 ). It's currently in a "barely usable" alpha state.

I've gotten to the point where the type checker implementation has become "nuanced" and having an actual formal specification for the type definition language would be very useful.

I'm not sure if progress has been made on a spec yet but there is still an old stub here ( https://github.com/jsigbiz/spec/blob/master/spec.md ).

It will be easier to verify a spec for the semantics of rtype/jsig now that we have a type checker we can use to execute the spec.

If anyone else is working on this I would love to collaborate.

**Comment by ericelliott** [comment]
@Raynos That is pretty much exactly what we're trying to accomplish in this repo.

We could use help formalizing it better. If you have suggestions, please feel free to submit pull requests.

If you would like your static type checker to work with `rtype`, I'm happy to support the effort in any way I can, and I'm happy to make you a collaborator on the `rtype` project.

**Comment by junosuarez** [comment]
While I remain very interested in typing and related tooling, I do not currently have the availability to contribute actively in JavaScript. Cheers!

**Comment by ericelliott** [comment]
@Raynos Are you still interested in working on this?

**Comment by Raynos** [comment]
@ericelliott I'm currently focused on the type checker and have not started looking into changing the jsig language yet or using a different type definition language.

I was going to write a formal definition of the type system, but I've punted and am working on more feature parity on the type checker itself.

**Comment by ericelliott** [comment]
@Raynos I'm definitely interested if you want to update it to add rtype support. Is your formal definition online somewhere? Maybe we can fork it and bring it into parity with rtype?

**Comment by ericelliott** [comment]
@Raynos Also, thanks for the update! =)

**Comment by Raynos** [comment]
@ericelliott Right now the type checker is like PHP, the formal definition is in the source code and the tests ( https://github.com/Raynos/jsig2 ).

I'm aiming to get a 0.2.0 build where I can have a full reference library type checked. I updated my README to mark the 0.2.0 milestone.

**Comment by ericelliott** [comment]
Let's track this in #89 going forward.
