### ISSUE TITLE
document when keyword interface is required

### ISSUE THREAD

**Issue by maiermic** [ericelliott/rtype#65]
According to [this](https://github.com/ericelliott/rtype/issues/55#issuecomment-174379537) comment `interface` is not required in some cases:

> - The `interface` keyword is implied for function signatures.

Since you [cann't declare properties without curly brackets](https://github.com/ericelliott/rtype/issues/55#issuecomment-174630627), `interface` is not needed to declare a type/interface:

``` TS
interface UserInstance {
  username: String,
  credentials: String
}
```

could also be written like this

```
UserInstance {
  username: String,
  credentials: String
}
```

Please clarify/document when the keyword `interface` is required?

**Comment by ericelliott** [comment]
The `interface` keyword is primarily useful to provide visual contrast between function signatures and other types, since function signatures play such a critical role in documentation, and they need to presented as directly as possible (without additional syntax / keyword noise).

Hence, we intentionally make the other type declarations a little more noisy in order to draw the distinction.

It's probably true that non-callable interfaces could be recognized without the `interface` keyword, if it were allowed, but currently, it is not. Hence:

``` js
// Error: Missing function signature.
UserInstance {
  username: String,
  credentials: String
}
```

**Comment by Mouvedia** [comment]
`type` would probably have been better but less encompassing.

Are there things not covered by regular function signatures that require the usage of `interface`?

**Comment by ericelliott** [comment]
Everything that is not a function signature requires the `interface` keyword.

**Comment by Mouvedia** [comment]
Then functions don't need to have another way of being expressed. It can be an internal thing not exposed to the user.
Which means that `interface` can only be contrived to describing user defined types, correct?
If that's the case why didn't you pick `type` as the keyword instead of `interface`?

I have shown a friend of mine a documentation in Rtype and his first question was "What's `interface`?"; it wouldn't have happened if it was called `type`…

**Comment by ericelliott** [comment]
> Then function don't need to have another way of being expressed.

Function signatures are a type of interface, and the `interface` keyword is currently the only way to express polymorphic signatures and properties attached to the function object.

As for `interface` vs `type`, I think the word `interface` is a better description than `type`. The word `type` (in my mind) implies that it's all about type checking, whereas `interface` makes implications about interface contracts. It's about the connotations.

Also, TypeScript uses `interface` in a similar way, so it may be familiar to some people. =)

**Comment by Mouvedia** [comment]
Good point about TypeScript.

But I am still favouring dropping the use of `interface` for functions, **externally**, since it's not granting the user anything more than he could using the lighter signature. It just complicates things further: KISS.

<del>So for example I would remove the examples that use `({…})` in the beginning of the README. Why it's also valid is never explained to the user: it's confusing and an unnecessary complication. Unless you have a really good reason to maintain that ambiguity, Ill make a PR this week.</del>

**Comment by ericelliott** [comment]
> But I am still favouring dropping the use of interface for functions

How would polymorphic functions be expressed?

>  I would remove the examples that use ({…}) in the beginning of the README

Which examples, specifically?

**Comment by Mouvedia** [comment]
> Which examples, specifically?

ctrl-f ({ the first 3

> How would polymorphic functions be expressed?

That's off topic. I don't want to derail this issue. Polymorphism is pretty rare IMHO. Since I can't come up with real use cases I am not qualified to answer it anyway.

Polymorphic functions have a named interface, which purpose is to be reused, I suppose. If you are using that function only once could the interface be nameless?

**Comment by Mouvedia** [comment]
> Which examples, specifically?

Sorry I didn't read carefully enough. Those are destructuring examples.

> How would polymorphic functions be expressed?

That's off topic. I don't want to derail this issue. Polymorphism is pretty rare IMHO. Since I can't come up with real use cases I am not qualified to answer it anyway.

Polymorphic functions have a named interface, which purpose is to be reused, I suppose. If you are using that function only once could the interface be nameless?

**Comment by ericelliott** [comment]
I'm confused. What is it exactly that you want to change? You want to make it illegal to use the `interface` keyword to describe functions? That won't work because the `interface` keyword is currently the only way to express:
1. polymorphic signatures and
2. properties attached to the function object

**Comment by Mouvedia** [comment]
I shouldn't have hijacked his issue. I was just saying that having two ways of doing the most common use case is probably wrong. Since you worked your way to the simpler signature and not the other way around, it makes sense that you consider the duality a necessity.

**Comment by ericelliott** [comment]
> I was just saying that having two ways of doing the most common use case is probably wrong.

That's not the most accurate way to think of it. What we have is a long-form form that works for everything, and **a shortcut for the most common use-case**. Getting rid of the shortcut is a bad idea, IMO, and we can't get rid of the long-form because it's necessary for the extra features it provides.

**Comment by Mouvedia** [comment]
https://github.com/ericelliott/rtype/issues/65#issuecomment-175301426
https://github.com/ericelliott/rtype#function-interface
