### ISSUE TITLE
anonymous rest arguments

### ISSUE THREAD

**Issue by maiermic** [ericelliott/rtype#79]
Since parameter names can be omitted (see [Anonymous Parameters](https://github.com/ericelliott/rtype#anonymous-parameters)), how do I type rest arguments anonymously? How about:

**Named:**

``` JS
(...args: Any[]) => Array
```

**Anonymous:**

``` JS
(...Any) => Array
```

**Comment by ericelliott** [comment]
IMO, this adds needless complexity to the spec. Why not simply use the very generic `args` name?

I'd say, stick with `(...args: Any[]) => Array`.

**Comment by maiermic** [comment]
If you omit the parameter name in

``` JS
(...args: Any[]) => Array
```

you get

``` JS
(Any[]) => Array
```

which is not the same type. Another suggestion would be:

``` JS
(...Any[]) => Array
```

IMO, this would be more consistent since `...` does not really belong to the name of the parameter. It just declares the parameter as rest parameter. If you use the rest parameter, you just write `args` instead of `...args`, which is something different (due to the spread operator).

After all, I would give this issue a low priority :sweat_smile:

**Comment by Mouvedia** [comment]
> `...` does not really belong to the name of the parameter.

That's the real problem then.
Is `(args: ...Any[]) => Array` what you want?

**Comment by ericelliott** [comment]
> Is (args: ...Any[]) => Array what you want?

No. The current correct syntax is:

``` js
(...args: Any[]) => Array
```

I don't see a good reason to complicate parsing just so we can add the potentially confusing shortcut `(...Any[]) => Array`.

**Comment by Mouvedia** [comment]
@ericelliott For the record, why is it the "correct" syntax?

@maiermic If we don't change the current syntax here's your answer:

```
(...: Any[]) => Array
```

**Comment by ericelliott** [comment]
> For the record, why is it the "correct" syntax?

Because that's what is currently specified, and because it makes sense.

This makes sense and should work:

``` js
(...: Any[]) => Array
```

**Comment by maiermic** [comment]
Sorry, but it doesn't make sense to me. Due to the colon it looks like `...` is the parameter name, which is invalid, since dots are not allowed in the name.

**Comment by ericelliott** [comment]
> Sorry, but it doesn't make sense to me. Due to the colon it looks like ... is the parameter name, which is invalid, since dots are not allowed in the name.

Since dots are not allowed in names, the ambiguity you mention doesn't exist at all...

I really think that confusion will fade very quickly with familiarity. I also don't think it's likely that it would confuse a lot of other people (because the ambiguity doesn't exist).

**Comment by ericelliott** [comment]
From chat:

When I say easy to parse, I'm not just talking about human parsing. I'm also talking about the parser itself. `(...Any[]) => Array` requires more complex lookahead rules than `(...: Any[]) => Array` because the former creates ambiguity. When we get to `Any` are we looking at a parameter name? (The default assumption). At what point can you discover that `Any` is actually the type annotation? Maybe when you hit the square brackets you can realize you've made a parsing mistake.... at which point you have to rewind the parser state.

In the `(...: Any[]) => Array` example, the parameter name is already optional, and the `:` disambiguates and makes it clear that `Any[]` is the type annotation. Which means there is no lookahead required, and there won't be a need to rewind the parser state.

A human being reading the signature might recognize the built-in `Any` type and assume that it's the type annotation, but _we can't disambiguate that way in the parser_, because some type names, such as `Any` and `Predicate` are perfectly valid parameter names.

I normally rate user friendliness over parser friendliness, but in this case, I feel that the `(...: Any[]) => Array` notation is _friendlier to users, too_, because it's logically consistent with the rest of the spec rules. In fact, _if we change nothing in the existing spec documentation_, that is currently legal syntax. If we wanted to make it illegal, we'd actually have to add a rule to the spec to do so.

Regardless of all that, I would still recommend that users stick to `(...args: Any[]) => Array` because there's no ambiguity, the intent is crystal clear, and it's only a few more keystrokes.

**Comment by Mouvedia** [comment]
If there's no objections I will proceed with the merge.
