### ISSUE TITLE
specify type of object's keys

### ISSUE THREAD

**Issue by maiermic** [ericelliott/rtype#99]
I propose the generic object type `Dictionary[Key, Value]` to define that all keys of an object should be of type `Key` and all values should be of type `Value`.

**Example from #98**

Type of

``` js
{
  joe: {
    skating: {time: 1000, money: 300},
    cooking: {time: 9999, money: 999}
  },
  emily: {
    running: {time: 300, money: 0}
  }
}
```

can be described as

``` scala
Dictionary[String, Dictionary[String, { time: Number, money: Number }]]
```

which can be splitted in smaller definitions using type aliases to provide more informative type names:

``` js
interface Name: String

interface Hobby: String

interface Expense {
    time: Number, money: Number
}

interface ExpBy_Hobby: Dictionary[Hobby, Expense]

interface ExpBy_Hobby_Person: Dictionary[Name, ExpBy_Hobby]
```

**Comment by ericelliott** [comment]
I like this.

**Comment by Mouvedia** [comment]
Is the `Dictionary` a `Map` or an `Object`?
It matters for the type of `Key`.

**Comment by Raynos** [comment]
at runtime it's `x instanceof Object`; aka a plain javascript object.

For `Map` it would just be `Map[String, Map[String, { time: Number, money: Number }]]`

**Comment by Mouvedia** [comment]
Then why would you need to introduce `Dictionary`? `Object` would do just fine.
If it was all encompassing that would make sense though.

**Comment by Raynos** [comment]
Correct; allowing `Object` to be both `Object` and `Object[String, X]` would do the trick. However that means you have a type name that is both generic and not generic at the same time.

`Dictionary[K, V]` and `Object[K, V]` express the same intent, however neither is documented in the README and this does cause confusion as there is no recommended way to handle this.

**Comment by Mouvedia** [comment]
I see the usage but I think we should first take care of #80; and once that's done, discuss #97 and this one at the same time.

**Comment by maiermic** [comment]
TypeScript calls it [indexable types](https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types) and uses this syntax

``` ts
interface ExpBy_Hobby_Person {
  [name: string]: {
    [hobby: string]: {
      time: number,
      money: number
    }
  }
}

var obj: ExpBy_Hobby_Person = {
  joe: {
    skating: {
      time: 1000,
      money: 300
    },
    cooking: {
      time: 9999,
      money: 999
    }
  },
  emily: {
    running: {
      time: 300,
      money: 0
    }
  }
};
```

which looks similar to [computed property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names) in object literals.

**Comment by Mouvedia** [comment]
I think the nesting doesn't hurt the readability.
Since we kept the keyword `interface` in place of `type` to help the developers familiar with typescript transition easily, we could also adopt this syntax if it meets all of our requirements.

The only additions that I would introduce are:
- a default syntax if the type of the key is a string and a label exists
- only 2 types allowed for the property key: String, Symbol cf https://github.com/ericelliott/rtype/issues/97#issuecomment-230130868
- only 3 types allowed for the property name: String, Number and regex literal cf https://github.com/ericelliott/rtype/issues/97#issuecomment-230132233

I am probably gonna do a PR that addresses all of these issues at once which would hopefully close #97, #98 and #99 if there's an agreement.
